language: go
sudo: required
addons:
  apt:
    packages:
    - unzip
    - curl
before_install:
- "./.travis_before_install.sh"
script:
- make deps
- make
- make test
go:
- 1.10.x
notifications:
  slack:
    secure: gtcz8aKMAHDLxzZvXzaPpWXCwr6dcHPCa+9CSP5aWZt32sv3YgoAcPGiJbkfAEtFiatMg8cQpeS+LqaxhhNeUnP4vTRWh99kJcNafAFk9DVjVmZwowsxaqMb5vJs16qw/oSu7S9Lj82nRZAAV8fnlm+MQtH5Q/zimuPn0T8uGDBupB3a2NPztbarFA3WgQ+zY9hlSYuzyOE6ssezBOa3SIRyJuzos2ariTWi+iVCUoxkg/DzNHOZKUOfT75V+D0ZLcIGsvGp9GCBFoFGB6PhwdkWMIRavXTs1cwq17FOQDM+pAx1nco3n8XZKLN53M2xNtXw70rXCthfIFWxjzJ4TZz5EoPu6mLdxgC5JAzw9F79kpsViE9m9YxaCdD/kxEwwssDvTj8kIitw8ztpBnPM7YxrDs2Pl2ypnbq3mAbCTh20Y2GS+iZDewPdjE00eQXk6GjAIMxjIWG2omzufiddL8EcXYsUkqrVK/JnvUNF8pvBY6X7hbpcrK/N45VR1nHH4pSyymN1owFQE2OZ12nr/38NFu6f0YNRjMagiLkp194iH/9pdXHlExbIzgaXTTBDRJHeOCi07lgDASkuj6WUVKdiYSQXj/SAiEK+ky9qOqzMuehwQMuPuFOGbjAfjMK54TwhmZRInQq0sVbTgYyzHx2DxIX2xNyQojxnyYbMp4=
